<?php
// Adminer Plugins Configuration
// Auto-generated by AdminerModule
// This file is automatically created and managed by the AdminerModule class

// Load plugin files
require_once __DIR__ . '/adminer-plugins/login-auto.php';
require_once __DIR__ . '/adminer-plugins/frames.php';
require_once __DIR__ . '/adminer-plugins/dark-switcher.php';
require_once __DIR__ . '/adminer-plugins/dump-zip.php';
require_once __DIR__ . '/adminer-plugins/dump-json.php';
require_once __DIR__ . '/adminer-plugins/tables-filter.php';
require_once __DIR__ . '/adminer-plugins/edit-textarea.php';
require_once __DIR__ . '/adminer-plugins/dump-date.php';

// Return array of plugin instances
return array(
    new AdminerLoginAuto(), // Must be first for auto-login
    new AdminerFrames(),
    new AdminerDarkSwitcher(),
    new AdminerDumpZip(),
    new AdminerDumpJson(),
    new AdminerTablesFilter(),
    new AdminerEditTextarea(),
    new AdminerDumpDate(),
);

